version: '3.3'

volumes:
  pg_data_foodgram:
  static_food:
  media_food:


services:
  db_foodgram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    image: prioritylonely/foodgram_backend
    env_file: .env
    depends_on:
      - db_foodgram
    volumes:
      - static_food:/static
      - media_food:/app/media
  frontend:
    container_name: foodgram-front
    image: prioritylonely/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_food:/frontend_static
  nginx:
    container_name: foodgram-proxy
    depends_on:
      - backend
    image: prioritylonely/foodgram_gateway
    ports:
      - "9100:80"
    volumes:
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_food:/static
      - media_food:/media 