version: '3.3'

volumes:
  pg_data_foodgram:
  static_food:
  media_food:


services:
  db_foodgram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    build: ../backend
    env_file: .env
    depends_on:
      - db_foodgram
    volumes:
      - static_food:/app/static
      - media_food:/app/media
  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_food:/frontend_static
  nginx:
    container_name: foodgram-proxy
    depends_on:
      - backend
    build: .
    ports:
      - "9100:80"
    volumes:
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_food:/static
      - media_food:/media 